// <auto-generated />
using System;
using MetroClaim.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MetroClaim.Api.Migrations
{
    [DbContext(typeof(MetroClaimDbContext))]
    [Migration("20251128095652_SeedDataUserAndAccount")]
    partial class SeedDataUserAndAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MetroClaim.Api.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("Expired")
                        .HasColumnType("datetime2")
                        .HasColumnName("expired");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("is_used");

                    b.Property<string>("Otp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("otp");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3578),
                            IsActive = true,
                            IsUsed = false,
                            PasswordHash = "0",
                            UpdatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3579),
                            UserId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3583),
                            IsActive = true,
                            IsUsed = false,
                            PasswordHash = "0",
                            UpdatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3583),
                            UserId = new Guid("a0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3585),
                            Expired = new DateTime(2025, 11, 28, 10, 6, 49, 796, DateTimeKind.Utc).AddTicks(3586),
                            IsActive = true,
                            IsUsed = false,
                            Otp = "123456",
                            PasswordHash = "0",
                            UpdatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3585),
                            UserId = new Guid("a0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3592),
                            Expired = new DateTime(2025, 11, 28, 9, 36, 49, 796, DateTimeKind.Utc).AddTicks(3593),
                            IsActive = true,
                            IsUsed = true,
                            Otp = "999999",
                            PasswordHash = "0",
                            UpdatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3592),
                            UserId = new Guid("a0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3594),
                            IsActive = true,
                            IsUsed = false,
                            PasswordHash = "0",
                            UpdatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3594),
                            UserId = new Guid("a0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3597),
                            IsActive = false,
                            IsUsed = false,
                            PasswordHash = "0",
                            UpdatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3597),
                            UserId = new Guid("a0000000-0000-0000-0000-000000000006")
                        });
                });

            modelBuilder.Entity("MetroClaim.Api.Models.ApprovalLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("int")
                        .HasColumnName("action");

                    b.Property<Guid>("ActionByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("action_by_user_id");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ReimbursementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reimbursement_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ActionByUserId");

                    b.HasIndex("ReimbursementId");

                    b.ToTable("approval_logs", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Disbursement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("amount_paid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ProcessedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("processed_by_user_id");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reference_number");

                    b.Property<Guid>("ReimbursementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reimbursement_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedByUserId");

                    b.HasIndex("ReimbursementId")
                        .IsUnique();

                    b.ToTable("disbursements", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Reimbursement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfExpense")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_expense");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Receipt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("receipt");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("reimbursements", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bank_account_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("employee_id");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("manager_id");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("ManagerId");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            BankAccountNumber = "1000000000",
                            CreatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3522),
                            Email = "admin@metroclaim.com",
                            EmployeeId = "ADM001",
                            Fullname = "System Administrator",
                            Role = 3,
                            UpdatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3524)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            BankAccountNumber = "2000000000",
                            CreatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3530),
                            Email = "manager@metroclaim.com",
                            EmployeeId = "MGR001",
                            Fullname = "John Manager",
                            Role = 1,
                            UpdatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3530)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            BankAccountNumber = "3000000000",
                            CreatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3533),
                            Email = "finance@metroclaim.com",
                            EmployeeId = "FIN001",
                            Fullname = "Sarah Finance",
                            ManagerId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Role = 2,
                            UpdatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3533)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            BankAccountNumber = "4000000000",
                            CreatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3536),
                            Email = "alice@metroclaim.com",
                            EmployeeId = "EMP001",
                            Fullname = "Alice Employee",
                            ManagerId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Role = 0,
                            UpdatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3536)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            BankAccountNumber = "5000000000",
                            CreatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3538),
                            Email = "bob@metroclaim.com",
                            EmployeeId = "EMP002",
                            Fullname = "Bob Employee",
                            ManagerId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Role = 0,
                            UpdatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3538)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            BankAccountNumber = "6000000000",
                            CreatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3541),
                            Email = "charlie@metroclaim.com",
                            EmployeeId = "EMP003",
                            Fullname = "Charlie Inactive",
                            ManagerId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Role = 0,
                            UpdatedAt = new DateTime(2025, 11, 28, 9, 56, 49, 796, DateTimeKind.Utc).AddTicks(3541)
                        });
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Account", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("MetroClaim.Api.Models.Account", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.ApprovalLog", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.User", "ActionByUser")
                        .WithMany("ApprovalLogs")
                        .HasForeignKey("ActionByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MetroClaim.Api.Models.Reimbursement", "Reimbursement")
                        .WithMany("ApprovalLogs")
                        .HasForeignKey("ReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionByUser");

                    b.Navigation("Reimbursement");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Disbursement", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.User", "ProcessedByUser")
                        .WithMany("ProcessedDisbursements")
                        .HasForeignKey("ProcessedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MetroClaim.Api.Models.Reimbursement", "Reimbursement")
                        .WithOne("Disbursement")
                        .HasForeignKey("MetroClaim.Api.Models.Disbursement", "ReimbursementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessedByUser");

                    b.Navigation("Reimbursement");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Reimbursement", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.Category", "Category")
                        .WithMany("Reimbursements")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithMany("Reimbursements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.User", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.User", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Category", b =>
                {
                    b.Navigation("Reimbursements");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Reimbursement", b =>
                {
                    b.Navigation("ApprovalLogs");

                    b.Navigation("Disbursement");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.User", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("ApprovalLogs");

                    b.Navigation("ProcessedDisbursements");

                    b.Navigation("Reimbursements");

                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
